// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'


    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7p-Isf4pDF9NQD05vA5JaxpnBO6yMEMg',
    appId: '1:1028860327492:web:a824ef56de331aa28aee11',
    messagingSenderId: '1028860327492',
    projectId: 'exhibitionqr-b20b2',
    authDomain: 'exhibitionqr-b20b2.firebaseapp.com',
    storageBucket: 'exhibitionqr-b20b2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYQRYI35UbzEghJmdXlZkkXZ7HVCXIXLk',
    appId: '1:1028860327492:android:f26464fe674da2e08aee11',
    messagingSenderId: '1028860327492',
    projectId: 'exhibitionqr-b20b2',
    storageBucket: 'exhibitionqr-b20b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhGjJV2qsMq-zBsqTb-OddPcOkfiE4veY',
    appId: '1:1028860327492:ios:04f20bb3e80f88fb8aee11',
    messagingSenderId: '1028860327492',
    projectId: 'exhibitionqr-b20b2',
    storageBucket: 'exhibitionqr-b20b2.firebasestorage.app',
    iosBundleId: 'com.example.exhibitionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhGjJV2qsMq-zBsqTb-OddPcOkfiE4veY',
    appId: '1:1028860327492:ios:04f20bb3e80f88fb8aee11',
    messagingSenderId: '1028860327492',
    projectId: 'exhibitionqr-b20b2',
    storageBucket: 'exhibitionqr-b20b2.firebasestorage.app',
    iosBundleId: 'com.example.exhibitionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7p-Isf4pDF9NQD05vA5JaxpnBO6yMEMg',
    appId: '1:1028860327492:web:df72b9744c9a005b8aee11',
    messagingSenderId: '1028860327492',
    projectId: 'exhibitionqr-b20b2',
    authDomain: 'exhibitionqr-b20b2.firebaseapp.com',
    storageBucket: 'exhibitionqr-b20b2.firebasestorage.app',
  );

}